enh(driver):C# 3.0 support publish nupkg with taosws.dll and libtaos.so
taosdata/taos-connector-dotnet pull request #38
Opened 2022-10-19 07:17 UTC by xleili

2022-10-19 08:26 UTC, sangshuduo approved these changes
LGTM

2022-10-20 06:30 UTC, zitsen requested changes

2022-10-20 06:30 UTC, zitsen commented on src/TDengine.csproj
> +    <None Include="runtimes/**" Pack="True" PackagePath="runtimes" />
Add possible changes for user project in the README.

2022-10-28 05:55 UTC, zitsen approved these changes
LGTM

2022-10-28 05:55 UTC, merged