fix: Fix null reference exception in setter that sets DbConnection property of the TDengineCommand class.
taosdata/taos-connector-dotnet pull request #90
Opened 2024-11-05 07:08 UTC by PopeyeZhong

var command = new TDengineCommand()
{
	CommandText = "...",
	CommandType = CommandType.Text,
};

var connection = new TDengineConnection("...");
command.DbConnection = connection;

上述代码片段中最后一行代码，因为 TDengineConnection 尚未打开，所以其内部的 client 变量为空，故而导致 TDegnineCommand.DbConnection 属性设置器中的代码引发了空引用异常。

现将 TDengineCommand 类中的 DbConnection 属性的设置器中的 _connection.client.StmtInit() 调用移动到  Statement() 方法中，将 StmtInit() 方法后置到执行方法也更为合理。

2024-11-11 02:03 UTC, PopeyeZhong commented
Can someone please help me with the code pull request approvals?

2024-11-26 07:46 UTC, huskar-t commented
@PopeyeZhong Can you add some unit tests to cover it?

2024-11-27 01:14 UTC, huskar-t commented
@PopeyeZhong Please rebase the 3.0 branch.

2024-11-27 01:48 UTC, PopeyeZhong commented
> @PopeyeZhong Can you add some unit tests to cover it?

Okay, I've added two unit test cases for TDengineCommand, please check them:
1. SetConnection_DoesNotThrowException
2. ExecuteNonQuery_WithDBNull

2024-11-27 01:52 UTC, PopeyeZhong commented
> @PopeyeZhong Please rebase the 3.0 branch.

YES, I just checked and it's based on the 3.0 branch.

2024-11-27 02:43 UTC, huskar-t commented on test/Data.Tests/TDengineCommandTests.cs
> +		[Fact]
Please format the code

2024-11-27 02:43 UTC, huskar-t requested changes
format the test code

2024-11-27 03:33 UTC, PopeyeZhong commented on test/Data.Tests/TDengineCommandTests.cs
> +		[Fact]
好的哈~

2024-11-27 03:46 UTC, PopeyeZhong commented
> format the test code

Done! please check it.

2024-11-27 04:46 UTC, huskar-t approved these changes

2024-11-27 05:37 UTC, merged